

server:
  port: 9091

spring:
  application:
    name: 'KafkaProducer'
  kafka:
    producer:
      acks: all
      client-id: kafkaproducerone
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers:
      - localhost:9091
      - localhost:9092
      - localhost:9093